import { IconAI, IconCode, IconChat, IconIndustry, IconCloud, IconDesktop } from './icons'

export const projets = [
  {
    id: 1,
    num: '01',
    title: 'Chatbot Documentaire Multimodal – Assistant IA Industriel QMS',
    cat: 'ia-web',
    status: 'Terminé', // ou 'En cours' selon toi
    image: '/chat3.png', // chemin corrigé
    dur: '2 Mois',
    type: 'Projet industriel',
    desc: `Ce projet est un assistant IA conçu pour rendre instantanément exploitable toute base documentaire industrielle, aussi dense et hétérogène soit-elle. L'utilisateur interroge en texte ou en voix, joint une image d'un document scanné ou d'un schéma technique : le système transcrit, extrait le texte de l'image, puis interroge le corpus via un moteur RAG hybride pour retourner une réponse précise dans la langue de l'utilisateur tout en citant le document, la page et le paragraphe exacts. Il génère et vérifie des FMEA à partir des templates existants, prépare des sessions d'audit et s'intègre nativement à SharePoint en respectant les droits d'accès. Contrairement aux chatbots généralistes, le système n'hallucine jamais : si la confiance est faible, il répond explicitement "non trouvé". La solution dispose également d'une couverture trilingue FR/EN/AR et d'une assistance vocale optionnelle, lui permettant d'être adoptée par tout type de profil utilisateur.`,
    stack: 'Réponses sourcées (doc + page + paragraphe)·Voix & image en entrée·RAG hybride dense + lexical·Génération et vérification FMEA·Assistant audit QMS·Intégration SharePoint·Anti‑hallucination·Trilingue FR / EN / AR',
    tech: 'Python·LangChain·FastAPI·SQL·Docker·ReactJs·Ollama',
    demo: '#',
    github: 'https://github.com/SouleymaneDiallo04/QMS_Chatbot',
    icon: '🧠',
    bg: 'rgba(99,102,241,.1)',
  },
  {
    id: 2,
    num: '02',
    title: 'AiThinkDesign – Plateforme IA Multi-Agents de Prototypage Digitale',
    cat: 'ia-web',
    status: 'Termine',
    image: '/aithinkdesign.jpeg',
    dur: '4 Mois',
    type: '3 Personnes',
    desc: `AiThinkDesign est une plateforme SaaS B2B conçue et vendue à l'entreprise SigmaXIs pour résoudre un problème structurel de l'industrie : le cycle de conception produit, encore largement artisanal, mobilise des semaines d'expertise humaine dispersée avant de produire un premier prototype exploitable. Notre solution réduit ce cycle à quelques heures en orchestrant plus de 30 agents spécialisés qui reproduisent, en parallèle et en continu, la démarche complète d'un bureau d'études pluridisciplinaire. Six personas créatives explorent l'espace des solutions, la méthode TRIZ résout les contradictions techniques identifiées, le Six Sigma valide la robustesse des concepts retenus, et treize analyses DFX sectorielles, couvrant l'aéronautique, l'automobile, le médical, l'électronique et l'ameublement, pour évaluer la fabricabilité sous tous les angles. La plateforme génère en sortie l'ensemble des livrables attendus par un décideur industriel : nomenclature chiffrée avec prix fournisseurs réels, coût de revient décomposé, plan de validation, visualisation 3D du prototype et exports professionnels prêts pour un comité de direction. L'intégralité du raisonnement est traçable et sourcée grâce à un moteur de connaissances sectoriel alimenté par les normes, brevets et retours d'expérience du domaine. Le résultat : un passage accéléré et maîtrisé de l’idée brute au prototype validé, en une fraction du temps habituel, et ce, sans ne rien perdre de la rigueur industrielle, ni de dépendre d’une expertise humaine dispersée.`,
    stack: 'Orchestration de 30+ agents IA en temps réel·Résolution de contradictions téchniques par la méthodologie TRIZ·Idéation multi-personas en parallèle·13 analyses DFx par secteur·Nomenclature chiffrée avec prix fournisseurs réels·Visualisation 3D et fichier CAO exportable (STEP/STL)', 
    tech: 'FastAPI·LangGraph·FreeCAD API·Next.js·TRIZ API·LangChain·PostgreSQL·CAO 3D',
    demo: '#',
    github: 'https://github.com/SouleymaneDiallo04/AITHINKDESIGN',
    icon: '🏭',
    imgPos: '50% 50%',
    imgFit: 'scale-down' as const,
    imgBg: '#ffffff',
    bg: 'rgba(99, 102, 241, 0.1)',
  },
  {
    id: 3,
    num: '03',
    title: 'AI SmartHub : Plateforme Intelligente de Gestion et Valorisation des Données IATD',
    cat: 'fullstack',
    status: 'Livré',
    image: '/smarthub1.png',
    dur: '3 Mois',
    type: '2 Personnes',
    desc: `AI SmartHub est une plateforme innovante qui centralise l’ensemble des ressources pédagogiques, projets étudiants, stages, mémoires et publications de la filière IATD. L’originalité majeure réside dans l’intégration de trois agents d’intelligence artificielle fonctionnant entièrement en local via Ollama (LLaMA 3 / Mistral), garantissant la souveraineté des données. L’agent de génération de quiz transforme n’importe quel contenu de cours en exercices interactifs (QCM, vrai/faux, questions ouvertes). L’agent de recherche intelligente interprète les requêtes en langage naturel et retourne les ressources les plus pertinentes. Enfin, l’agent de recommandation personnalisée apprend des interactions de chaque étudiant pour suggérer des contenus et offres adaptés. Cette plateforme démontre concrètement comment l’IA peut enrichir l’apprentissage de manière éthique, transparente et maîtrisée.`,
    stack: 'Gestion centralisée des cours·Suivi des projets étudiants·Bibliothèque de mémoires et publications·Génération automatique de quiz par IA·Recherche sémantique et contextuelle·Recommandation personnalisée·Espace étudiant, enseignant et administrateur·Système d’annonces et actualités',
    tech: 'Spring Boot·React·PostgreSQL·Ollama·Spring Security·Maven',
    demo: '#',
    github: 'https://github.com/SouleymaneDiallo04/AI-SmartHub',
    icon: '🤖',
    imgPos: '50% 50%',
    imgFit: 'scale-down' as const,
    imgBg: '#ffffff',
    bg: 'rgba(0,150,100,.1)',
  },
  {
    id: 4,
    num: '04',
    title: 'PrognoSense – Plateforme Intelligente de Maintenance Prédictive par Analyse Vibratoire',
    cat: 'ia-mobile',
    status: 'Terminé',
    image: '/progno1.png',
    dur: '2 Mois',
    type: 'Personnel',
    desc: `Ce projet consiste en la conception et le développement d'une plateforme web de maintenance prédictive qui transforme des signaux vibratoires bruts en stratégies d'intervention anticipée. Le système analyse en continu les données de capteurs industriels, calcule un Health Index temps réel pour chaque machine et prédit sa durée de vie utile restante (RUL) via un benchmark de cinq modèles IA sélectionnable en un clic. Sa détection d'anomalies repose sur un Autoencoder PyTorch capable d'identifier des défauts jamais vus dans les données historiques, là où les approches classiques restent aveugles. L'interface offre une analyse spectrale FFT, un laboratoire IA pour comparer et basculer entre modèles instantanément, un module de simulation pour tester les seuils avant déploiement, et un Assistant Copilot qui génère les rapports et des recommandations opérationnelles avec actions, délais et niveau de confiance.  L'objectif est de permettre aux équipes de maintenance de passer d'une approche réactive ou calendaire à une maintenance véritablement prédictive, réduisant ainsi les arrêts non planifiés et les coûts de maintenance et améliorant la disponibilité des équipements.`,
    stack: 'Health Index continu avec 4 seuils sémantiques d\'intervention·Détection d\'anomalies non supervisée via Autoencoder·Prédiction du Remaining Useful Life (RUL)·Benchmark dynamique de 5 architectures·Analyse spectrale FFT avec identification des fréquences de défaillance·Assistant conversationnel IA·Génération automatique de rapports de maintenance par machine ·Alertes email en cas de panne imminente',
    tech: 'Python·FastAPI·React·Scikit-learn·MLOps·SQLite·Scipy·PyTorch',
    demo: '#',
    github: 'https://github.com/SouleymaneDiallo04/Plateforme-de-Maintenance-Predictive-Industrielle',
    icon: '⚙️',
    imgPos: '50% 50%',
    imgFit: 'scale-down' as const,
    imgBg: '#0e1120',
    bg: 'rgba(67, 230, 200, 0.1)',
  },
   {
    id: 5,
    num: '05',
    title: 'Grenier Commun – La Première Infrastructure Agricole Digitale d\'Afrique de l\'Ouest',
    cat: 'ia-web',
    status: 'Terminé',
    image: '/grenier.png',
    dur: '2 Mois',
    type: 'Personnel',

    desc: `Au Sénégal, des milliers de petits agriculteurs subissent chaque saison la même triple injustice : vendre contraint au pire moment faute de stockage, perdre 30 à 40 % de leur récolte  à cause de greniers inadaptés, et se voir refuser tout accès au crédit bancaire faute de garanties formelles. C'est de ce constat que m'est venue l'idée de Grenier Commun,  la première plateforme intégrée d'Afrique de l'Ouest qui résout ces trois problèmes en un seul produit. Reposant sur un réseau de silos physiques connectés, elle permet à l'agriculteur de stocker sa récolte, d'emprunter jusqu'à 70 % de la valeur de son stock via le warrantage numérique, et de vendre au bon moment grâce à des recommandations IA hebdomadaires. La plateforme orchestre cinq espaces utilisateurs distincts : agriculteur, gestionnaire de silo, acheteur, institution de microfinance et administrateur , tous assistés par un chatbot IA contextuel qui accède aux données réelles de la plateforme via 15 outils métier et répond dans la langue de l'utilisateur. Nativement multilingue, elle supporte le français, l'anglais, l'arabe et le Wolof, langue locale pratiquée par plus de 80 % des Sénégalais,  grâce à une infrastructure de traduction à trois niveaux combinant Django i18n, Google Translate et le modèle Meta NLLB-200. Car une infrastructure digitale  n'a de sens que si elle parle la langue de ceux pour qui elle a été construite. Avec Grenier_Commun, chaque maillon de la chaîne agricole est désormais connecté, tracé et optimisé.`,

    stack: `Interface native multilingue : Français, Anglais, Arabe et Wolof·Chatbot IA contextuel·Warrantage numérique·Price Predictor pour recommandations de vente hebdomadaires·Scoring crédit qui mesure la fiabilité de l'agriculteur·Notifications SMS multilingues·Reçus PDF et rapports mensuels automatisés`,
    tech: 'Django·PostgreSQL·Google Translate·Redis·Railway·Tailwind CSS·Meta NLLB-200·Twilio',

    demo: 'https://web-production-04b0a.up.railway.app',

    github: 'https://github.com/SouleymaneDiallo04/Grenier-Commun_Plateforme-Intelligente-de-Gestion-Post-recolte',
    icon: '🌾',
    imgPos: '50% 50%',
    imgFit: 'cover' as const,
    imgBg: '#f0f7f4',
    bg: 'rgba(29, 158, 117, 0.1)',
  },
  {
    id: 6,
    num: '06',
    title: 'Système de Surveillance Intelligent – Vision par Ordinateur',
    cat: 'ia-web',
    status: 'Terminé',
    image: '/chute2.jpg',
    dur: '3 Mois',
    type: '2 Personnes',
    desc: `Ce projet n'est pas une simple solution de télésurveillance : c'est un écosystème d'IA révolutionnaire conçu pour garantir la sécurité et la dignité des personnes âgées et des patients à risque. Le système intègre trois modèles d’IA de pointe : une détection de chûtes en temps réel, une détection de somnolence par analyse faciale et une prédiction de chûtes par analyse de séquences vidéo pour anticiper l'accident.  L'application, fluide et interactive, envoie des alertes instantanées en cas de risque imminent, offrant ainsi une véritable bouée de sauvetage technologique.`,
    stack: 'Détection de chutes en temps réel (YOLOv5)·Prédiction de chutes·Détection de somnolence·Interface utilisateur interactive·Alertes en temps réel·Architecture hybride CNN‑LSTM',
    tech: 'Python·YOLOv5·PyTorch·TensorFlow·Keras·OpenCV·MediaPipe·Streamlit',
    demo: 'https://computer-vision2.readthedocs.io/en/latest/',
    github: 'https://github.com/SouleymaneDiallo04/Systeme-de-Surveillance-de-la-Posture',
    icon: '👁️',
    imgPos: '50% 50%',
    imgFit: 'scale-down' as const,
    imgBg: '#1e1e1e',
    bg: 'rgba(0, 0, 0, 0.1)',
  },
  {
    id: 7,
    num: '07',
    title: 'AgriVision Pro – Application Mobile de Prédiction Agricole',
    cat: 'ia-mobile',
    status: 'Terminé',
    image: '/agrivision.jpg',
    dur: '1 Mois',
    type: 'Personnel',
    desc: `AgriVision Pro est une application mobile innovante conçue pour accompagner les agriculteurs dans la transition vers une agriculture de précision. Elle répond à trois besoins critiques : savoir quelle culture planter selon les caractéristiques du sol et du climat, anticiper les rendements pour mieux gérer les récoltes, et détecter rapidement les maladies des plantes à partir d’une simple image. La solution offre une interface intuitive et accessible, permettant aux utilisateurs de prendre des décisions éclairées pour une agriculture plus durable et productive.`,
    stack: 'Recommandation de cultures·Prédiction de rendement·Détection de maladies par image·Analyse des paramètres pédologiques et climatiques·Interface mobile cross‑platform·Backend Flask',
    tech: 'Flutter·Python·Flask·TensorFlow·Scikit-learn·YOLOv5',
    demo: '',
    github: 'https://github.com/SouleymaneDiallo04/AgriVision-Pro',
    icon: '📱',
    bg: 'rgba(76, 175, 80, 0.1)',
  },
  {
    id: 8,
    num: '08',
    title: 'StockFlow : Plateforme Intelligente de Gestion de stock industriel',
    cat: 'ia-web',
    status: 'Terminé',
    image: '/stock1.png',
    dur: '1 Mois',
    type: 'Projet Personnel',
    desc: `Ce projet consiste en la conception et le développement d’une plateforme web qui automatise et optimise la gestion des stocks par l’intelligence artificielle. Le système analyse les ventes passées, la saisonnalité et les tendances du marché pour anticiper de manière précise les futurs besoins de l'entreprise. Il détermine pour chaque produit les quantités à commander et les seuils de réapprovisionnement qui minimisent les coûts tout en maîtrisant le risque de rupture. L’objectif est double : éliminer d'abord les ruptures qui coûtent des ventes et ensuite réduire le surstockage, afin d’améliorer nettement la rentabilité opérationnelle. La plateforme intègre des modèles de prévision avancés (SARIMA, Prophet, LightGBM, TFT), une optimisation par simulation de Monte‑Carlo (10 000 scénarios), des cartes de contrôle SPC avec les 8 règles de Western Electric, et une classification ABC‑XYZ pour des recommandations de politiques adaptées. Le tout est orchestré par Celery, suivi par MLflow, et exposé via une interface web Django enrichie par HTMX et Plotly.`,
    stack: 'Prévision multi‑modèle de la demande·Optimisation par simulation Monte‑Carlo·Cartes de contrôle SPC·Classification ABC‑XYZ·Intégration de données externes·Dashboard interactif (Plotly, HTMX)',
    tech: 'Django·Celery·LightGBM·Prophet·PyTorch·MLflow·HTMX·SQLite',
    demo: '#',
    github: 'https://github.com/SouleymaneDiallo04/StockFlow-Plateforme-Intelligente-de-Gestion-de-stock-Industriel',
    icon: '📦',
    imgFit: 'scale-down' as const,
    imgPos: '50% 50%',
    imgBg: '#0e1120',
    bg: 'rgba(56, 161, 105, 0.1)',
  },
  {
    id: 9,
    num: '09',
    title: 'Bitcoin Price Prediction – Deep Learning & Social Sentiment',
    cat: 'ia-web',
    status: 'Terminé',
    image: '/bitcoin1.jpg',
    dur: '3 Mois',
    type: 'Personnel',
    desc: `La prédiction du prix du Bitcoin est un défi majeur en finance quantitative en raison de sa volatilité extrême et de sa sensibilité aux facteurs externes. Ce projet propose un système avancé de prévision basé sur les séries temporelles, fusionnant des architectures hybrides CNN‑LSTM avec un indice de sentiment social calculé en temps réel à partir des réseaux sociaux (Twitter, Reddit) via des techniques de NLP. Un assistant conversationnel personnalisé permet à l’utilisateur de recevoir des conseils d’achat ou de vente adaptés au marché, de comprendre la dynamique en temps réel, de recevoir des alertes et d’obtenir des explications détaillées sur les prédictions. L’ensemble est documenté via une documentation technique complète (ReadTheDocs) et déployé dans une application web interactive.`,
    stack: 'Architecture hybride CNN‑LSTM·Analyse du sentiment des réseaux sociaux·Assistant chatbot personnalisé·Scrapping de données·Documentation ReadTheDocs·Application web interactive',
    tech: 'Python·TensorFlow·NLP·Transformers·Scrapy·Scikit‑learn·Flask',
    demo: 'https://forecasting-du-prix-du-bitcoin.readthedocs.io/fr/latest/index.html',
    github: 'https://github.com/SouleymaneDiallo04/Forecasting-du-prix-du-Bitcoin',
    icon: '₿',
    bg: 'rgba(247, 147, 26, 0.1)',
  },

  {
    id: 10,
    num: '10',
    title: 'CityPulse Logistics – Plateforme Desktop d\'Optimisation de Tournées par IA',
    cat: 'ia-desktop',
    status: 'Terminé',
    image: '/city.png',
    dur: '1 Mois',
    type: '2 Personnes',
    desc: `Ce projet consiste en la conception et le développement d'une application desktop Python qui résout ce que des milliers de responsables logistiques font encore à la main chaque matin : planifier des tournées de livraison en jonglant entre créneaux clients, capacités des camions, réglementations ADR, délais de livraison et disponibilités des chauffeurs, souvent plusieurs heures de travail pour un résultat loin d'être optimal. CityPulse Logistics est la réponse à ce problème, le système lance simultanément trois algorithmes (VRP-Greedy, 2-Opt et Google OR-Tools) sur les mêmes données et présente un comparatif immédiat en termes de distance, coût, CO₂, conformité et contraintes routières. Il gère l'intégralité de la chaîne logistique entre clients, véhicules, chauffeurs, dépôts et commandes, avec une cartographie interactive, un suivi Gantt en temps réel et une génération automatique des rapports de tournées dans cinq langues possibles en fonction du choix de l'utilisateur. Un Chatbot IA assiste chaque décision en accédant au contexte complet de la flotte. Résultat : ce que vos équipes mettaient des heures à planifier, CityPulse le résout en quelques secondes.......et toujours mieux.`,
    stack: 'Benchmark simultané de 3 algorithmes·Assistant Conversationnel IA·ML embarqué (IsolationForest, ARIMA, ...)·Génération de rapports PDF·Plateforme multilingue (FR/EN/AR/ES/DE)·Comparatif visuel multi-critères',
    tech: 'PyQt6·Google OR-Tools·Mistral AI·ReportLab',
    demo: '#',
    github: 'https://github.com/SouleymaneDiallo04/CityPulse-Logistics',
    icon: '🚚',
    imgPos: '50% 50%',
    imgFit: 'cover' as const,
    imgBg: '#0D1B2A',
    bg: 'rgba(0, 212, 255, 0.1)',
  },
]

export const certifications = [
  { ico: '🏅', name: 'Machine Learning Specialization', issuer: 'Coursera — Andrew Ng', org: 'Coursera — DeepLearning.AI', year: '2024', status: 'Vérifié', score: '98/100', desc: 'Spécialisation en 3 cours couvrant supervised learning, unsupervised learning et reinforcement learning. Projets pratiques en Python avec TensorFlow et Scikit-learn.', link: 'https://coursera.org' },
  { ico: '☁️', name: 'AWS Cloud Practitioner', issuer: 'Amazon Web Services', org: 'Amazon Web Services', year: '2025', status: 'Vérifié', score: '890/1000', desc: 'Certification fondamentale AWS couvrant les services cloud, la sécurité, l\'architecture et la facturation. Valide une compréhension des services AWS et du déploiement cloud.', link: 'https://aws.amazon.com/certification' },
  { ico: '🤗', name: 'NLP with Transformers', issuer: 'Hugging Face', org: 'Hugging Face', year: '2024', status: 'Vérifié', score: 'Mention excellente', desc: 'Formation avancée sur les architectures Transformer, BERT, GPT et leurs applications en NLP. Fine-tuning de modèles pré-entraînés et déploiement d\'API.', link: 'https://huggingface.co/learn' },
  { ico: '📊', name: 'Google Data Analytics', issuer: 'Google / Coursera', org: 'Google / Coursera', year: '2024', status: 'Vérifié', score: '97/100', desc: 'Programme de 8 cours couvrant l\'analyse de données avec SQL, R, Tableau et Google Sheets. Projet capstone complet d\'analyse de données réelles.', link: 'https://grow.google/certificates/data-analytics' },
  { ico: '🎓', name: 'Diplôme Ingénieur IA', issuer: 'École d\'Ingénieurs', org: 'École d\'Ingénieurs, Maroc', year: '2026', status: 'En cours', score: '—', desc: 'Diplôme d\'ingénieur spécialité Intelligence Artificielle et Data Science. Formation de 5 ans incluant ML, DL, Big Data, MLOps et projets industriels.', link: '#' },
  { ico: '🐳', name: 'Docker & Kubernetes', issuer: 'Udemy — KodeKloud', org: 'Udemy — KodeKloud', year: '2025', status: 'Vérifié', score: 'Complété', desc: 'Formation complète sur la containerisation Docker et l\'orchestration Kubernetes. Docker Compose, volumes, réseaux, Helm charts et déploiement en production.', link: 'https://kodekloud.com' },
]

export const services = [
  {
    num: '01',
    ico: IconCode,
    title: 'IA / Data Science / ML',
    short: 'Modèles prédictifs, NLP et vision par ordinateur pour des décisions data-driven.',
    tags: ['PyTorch', 'HuggingFace', 'MLflow'],
    detail: `Ingénieur spécialisé en IA, je conçois des solutions algorithmiques sur mesure pour répondre aux enjeux stratégiques des entreprises. De la modélisation à l'automatisation, je traduis les données complexes en outils d'aide à la décision performants. Mon approche combine rigueur technique et vision métier pour livrer des systèmes robustes (recommandation, prédiction, vision) parfaitement intégrés à vos processus opérationnels.`,
    techs: ['TensorFlow ', 'PyTorch', 'Scikit-learn', 'MLflow', 'SQL']
  },
  {
    num: '02',
    ico: IconAI,
    title: 'Développement Web Full Stack',
    short: 'Interfaces réactives et APIs performantes, du design system au déploiement Cloud.',
    tags: ['React', 'Node.js', 'FastAPI', 'Docker', 'PostgreSQL'],
    detail: `Full Stack aguerri, je pilote l'intégralité du cycle : de la conception front-end à la mise en œuvre back-end, en passant par la gestion des bases de données et le déploiement sur infrastructure cloud. Fort d'une expertise dans les technologies modernes (Next.js, React, Node.js, Python/Django, SQL/NoSQL, etc.), je conçois des applications web performantes, scalables et sécurisées, pour une expérience utilisateur fluide et intuitive.`,
    techs: ['React', 'Node.js', 'FastAPI', 'Docker', 'PostgreSQL']
  },
  {
    num: '03',
    ico: IconChat,
    title: 'Chatbots & Agents IA',
    short: 'Agents LLM avec mémoire, RAG et appels d\'outils intégrés à vos systèmes.',
    tags: ['LangChain', 'LlamaIndex', 'Pinecone'],
    detail: `Je ne construis pas de simples chatbots, je conçois des agents autonomes capables de raisonner, de planifier et d'interagir avec vos systèmes existants. Architecture RAG sur vos documents internes, mémoire conversationnelle longue durée et des systèmes multi-agents pour orchestrer des tâches complexes. Chaque solution est optimisée pour fournir des réponses vérifiables et capables de s'intégrer nativement à vos outils de communication, transformant l'IA en un collaborateur opérationnel immédiat.`,
    techs: ['RAG', 'Ollama', 'LangGraph', 'Mistral', 'OpenAI', 'Pinecone']
  },
  {
    num: '04',
    ico: IconIndustry,
    title: 'Génie Industriel & Usine 4.0',
    short: 'Digitalisation des processus et optimisation des systèmes industriels.',
    tags: ['IIoT', 'Big Data', 'Systèmes Cyber-Physiques'],
    detail: `Ma double expertise en Génie Industriel et en Data Science me permet de transformer les flux physiques du terrain en modèles prédictifs exploitables. Je maîtrise l'ensemble de la chaîne de valeur, de l'instrumentation IoT à l'exploitation Big Data, pour passer du simple monitoring à un pilotage intelligent. C’est cette compréhension fine du terrain qui me permet de livrer des solutions digitales parfaitement alignées avec vos contraintes opérationnelles tout en maximisant la productivité.`,
    techs: ['IoT', 'PLC', 'SCADA', 'Big Data', 'Modbus']
  },
  {
    num: '05',
    ico: IconCloud,
    title: 'MLOps & Infrastructure Cloud',
    short: 'Industrialisation de modèles IA et gestion d’infrastructures Cloud.',
    tags: ['Azure', 'DevOps', 'MLflow'],
    detail: `Un modèle qui reste en notebook n'a aucune valeur métier : je le rends opérationnel. Je déploie des infrastructures sur AWS ou Azure en utilisant Terraform pour l'automatisation et Docker pour la conteneurisation. Grâce à l'orchestration sous Kubernetes, je transforme vos algorithmes en services scalables et monitorés. Du versioning avec MLflow à l'automatisation CI/CD, je sécurise l'intégralité du pipeline pour garantir une IA performante et fiable en production.`,
    techs: ['AWS / GCP', 'Docker', 'Kubernetes', 'MLflow ', 'Terraform']
  },
  {
    num: '06',
    ico: IconDesktop,
    title: 'Développement Desktop',
    short: 'Applications logicielles robustes, performantes et multiplateformes.',
    tags: ['Natif', 'Cross-platform', 'Outils Métiers'],
    detail: `Spécialiste en développement desktop, je conçois des solutions logicielles robustes et intuitives pour répondre à vos besoins métiers les plus exigeants. Fort de mon expertise en C++, Python et Java, je maîtrise aussi bien la création d'applications natives avec Qt que le déploiement de solutions multiplateformes modernes via Tauri ou Electron. Mon approche garantit des logiciels fluides, sécurisés et parfaitement optimisés, de l’architecture système jusqu'à l\'expérience utilisateur finale.`,
    techs: ['C++', 'Python', 'Java', 'Qt', 'Tkinter', '.NET']
  }
]

export const technologies = ['Python', 'PyTorch', 'TensorFlow', 'FastAPI', 'Next.js', 'LangChain', 'Docker', 'PostgreSQL', 'Scikit-learn', 'HuggingFace', 'Fly.io', 'Vercel']

export const typeStrings = ['Machine Learning Engineer', 'Data Scientist', 'NLP Specialist', 'AI Engineer', 'MLOps Practitioner']
